name: Java CI with Gradle

# ë™ì‘ ì¡°ê±´ ì„¤ì • : develop ë¸Œëœì¹˜ì— push í˜¹ì€ pull requestê°€ ë°œìƒí•  ê²½ìš° ë™ì‘í•œë‹¤.
on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  # Spring Boot ì• í”Œë¦¬ì¼€ì´ì…˜ì„ ë¹Œë“œí•˜ì—¬ ë„ì»¤í—ˆë¸Œì— í‘¸ì‹œí•˜ëŠ” ê³¼ì •
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    # 1. Java 17 ì„¸íŒ…
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # 2. Spring Boot ì• í”Œë¦¬ì¼€ì´ì…˜ ë¹Œë“œ
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: clean bootJar

    # 3. Docker ì´ë¯¸ì§€ íƒœê·¸ ì„¤ì •
    - name: Set Docker Image Tag
      id: docker_tag
      run: echo "DOCKER_IMAGE_TAG=${{ secrets.DOCKERHUB_USERNAME }}/rework-backend:${{ github.run_number }}" >> $GITHUB_ENV

    # 4. Docker ì´ë¯¸ì§€ ë¹Œë“œ
    - name: docker image build
      run: docker build -t ${{ env.DOCKER_IMAGE_TAG }} .

    # 5. DockerHub ë¡œê·¸ì¸
    - name: docker login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    # 6. Docker Hub ì´ë¯¸ì§€ í‘¸ì‹œ
    - name: docker Hub push
      run: docker push ${{ env.DOCKER_IMAGE_TAG }}

    # 7. ì„œë²„ì— ì ‘ì†í•˜ì—¬ ìŠ¤í¬ë¦½íŠ¸ ì‹¤í–‰
    - name: Deploy to Prod Server
      uses: appleboy/ssh-action@v1.0.3
      if: contains(github.ref, 'develop')
      with:
        host: ${{ secrets.MAIN_HOST }}
        username: ${{ secrets.MAIN_USERNAME }}
        key: ${{ secrets.MAIN_SSH_KEY }}
        port: 22
        script: |
          cd rework && sed -i "s/^BUILD_NUMBER=.*/BUILD_NUMBER=${{ github.run_number }}/" .env && ./deploy.sh
  
  send-discord-notification:
    runs-on: ubuntu-latest
    needs: build-docker-image
    steps:
      - name: Set Deployment Message
        id: set_message
        run: echo "::set-output name=message::ğŸš€${{ github.run_number }}ë²ˆì§¸ í”„ë¡œì íŠ¸ê°€ ì •ìƒì ìœ¼ë¡œ ë°°í¬ë˜ì—ˆìŠµë‹ˆë‹¤! ìµœì‹ í™” í™•ì¸ì„ ìœ„í•´ì„œ [ì—¬ê¸°](http://43.202.187.4/swagger-ui/index.html)ë¡œ ì´ë™í•´ì£¼ì„¸ìš”."
      - name: Discord Webhook Action
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          content: ${{ steps.set_message.outputs.message }}


